// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f79173c3-2562-4b58-aac0-1ff73dd1ef5d",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_18Jd33NPW",
    "aws_user_pools_web_client_id": "1ib3itkb88bih3llb4nkpkhh0l",
    "oauth": {},
    "aws_user_files_s3_bucket": "knightsarcade-s3",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
